# Configuration
# https://gohugo.io/getting-started/configuration/#all-configuration-settings

paginate = 5
enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true
defaultContentLanguage = 'pt'

## Permalinks
permalinks.posts = '/posts/:year/:month/:slug/'

## Hugo Modules
module.imports = [
	{ path = 'github.com/martignoni/hugo-notice' },
	{ path = 'github.com/adityatelange/hugo-PaperMod' },
]

## Outputs
outputs.home = [
	'HTML',
	'RSS',
	'JSON',
]

## Minify
minify.disableXML = true

## Markup
markup.goldmark.renderer.unsafe = true
markup.highlight.noClasses = false

## Privacy
privacy.vimeo.disabled = false
privacy.vimeo.simple = true
privacy.twitter.disabled = false
privacy.twitter.enableDNT = true
privacy.twitter.simple = true
privacy.instagram.disabled = false
privacy.instagram.simple = true
privacy.youtube.disabled = false
privacy.youtube.privacyEnhanced = true

## Services
services.instagram.disableInlineCSS = true
services.twitter.disableInlineCSS = true
