# Configuration
# https://gohugo.io/getting-started/configuration/#all-configuration-settings

enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true
defaultContentLanguage = 'pt'

pagination.pagerSize = 5

## Hugo Modules
module.imports = [
	{ path = 'github.com/adityatelange/hugo-PaperMod' },
]

## Outputs
outputs.home = [
	'HTML',
	'RSS',
	'JSON',
]

## Minify
minify.disableXML = true

## Markup
markup.goldmark.renderer.unsafe = true
markup.highlight.noClasses = false

## Privacy
privacy.vimeo.disabled = false
privacy.vimeo.simple = true
privacy.x.disabled = false
privacy.x.enableDNT = true
privacy.x.simple = true
privacy.instagram.disabled = false
privacy.instagram.simple = true
privacy.youtube.disabled = false
privacy.youtube.privacyEnhanced = true

## Services
services.instagram.disableInlineCSS = true
services.x.disableInlineCSS = true
